"""Render a KnowStack PR-context bundle JSON into a PR comment body.

Used by `.github/workflows/pr-context.yml`. Reads the JSON bundle from a path
(or stdin), prints markdown to stdout. Kept out of the workflow YAML so the
string handling and counts stay testable.

The output always starts with the marker `<!-- knowstack-pr-context -->`,
which the workflow uses to find and update an existing comment instead of
appending a new one on every push.
"""
from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

MARKER = "<!-- knowstack-pr-context -->"

# Display order for the breakdown table. Matches REASON_WEIGHT in
# knowstack/pr_context/budget.py so the comment mirrors selection priority.
REASON_ORDER = ("touched", "test", "caller", "callee", "impacted", "related_config")
REASON_LABEL = {
    "touched": "Touched (the diff itself)",
    "test": "Tests",
    "caller": "Direct callers",
    "callee": "Direct callees",
    "impacted": "Transitively impacted",
    "related_config": "Related configs",
}


def main(argv: list[str]) -> int:
    raw = _read_input(argv)
    try:
        bundle = json.loads(raw)
    except json.JSONDecodeError as exc:
        sys.stderr.write(f"format_comment: invalid JSON ({exc})\n")
        print(_empty_comment("Could not parse the context bundle (invalid JSON)."))
        return 0  # advisory action — never fail CI

    if bundle.get("empty"):
        print(_empty_comment("No file changes detected in this PR's diff."))
        return 0

    print(_render(bundle))
    return 0


# ── rendering ───────────────────────────────────────────────────────────────


def _render(bundle: dict) -> str:
    used = int(bundle.get("estimated_tokens", 0))
    budget = int(bundle.get("budget_tokens", 0))
    nodes = bundle.get("nodes", []) or []
    dropped = int(bundle.get("dropped_count", 0))
    notes = bundle.get("notes", []) or []
    seeds = bundle.get("seeds", []) or []
    context_text = bundle.get("context_text", "") or ""

    # Sort for stable rendering across runs (matters for the upsert check —
    # comment bodies should be deterministic for the same bundle).
    nodes = sorted(
        nodes,
        key=lambda n: (
            REASON_ORDER.index(n.get("reason", "related_config"))
            if n.get("reason") in REASON_ORDER else 99,
            int(n.get("distance", 0)),
            str(n.get("fqn", "")),
        ),
    )

    breakdown = Counter(n.get("reason", "?") for n in nodes)
    touched = [n for n in nodes if n.get("reason") == "touched"]

    parts: list[str] = [MARKER, "### KnowStack PR review context", ""]

    pct = (100 * used / budget) if budget else 0
    parts.append(
        f"**Budget:** {used:,} / {budget:,} tokens ({pct:.0f}%) "
        f"• **Selected:** {len(nodes)} nodes • **Dropped:** {dropped}"
    )
    parts.append("")

    if seeds:
        parts.append("**Touched symbols**")
        for s in seeds[:10]:
            parts.append(f"- `{s}`")
        if len(seeds) > 10:
            parts.append(f"- … and {len(seeds) - 10} more")
        parts.append("")

    if touched:
        parts.append("<details><summary>Touched symbol locations</summary>")
        parts.append("")
        for n in touched:
            loc = _loc(n)
            parts.append(f"- `{n.get('fqn', '')}` — `{loc}`")
        parts.append("")
        parts.append("</details>")
        parts.append("")

    parts.append("<details><summary>LLM-ready context (paste into your reviewer model)</summary>")
    parts.append("")
    parts.append("```markdown")
    parts.append(context_text.rstrip() or "(empty)")
    parts.append("```")
    parts.append("")
    parts.append("</details>")
    parts.append("")

    if breakdown:
        parts.append("<details><summary>Selection breakdown</summary>")
        parts.append("")
        parts.append("| Reason | Count |")
        parts.append("|---|---|")
        for r in REASON_ORDER:
            if breakdown.get(r):
                parts.append(f"| {REASON_LABEL[r]} | {breakdown[r]} |")
        parts.append("")
        parts.append("</details>")
        parts.append("")

    if notes:
        parts.append("**Notes**")
        for n in notes:
            parts.append(f"- {n}")
        parts.append("")

    parts.append("<sub>Generated by `knowstack pr-context` — edit `.github/workflows/pr-context.yml` to tune the token budget or model.</sub>")
    return "\n".join(parts)


def _loc(node: dict) -> str:
    fp = node.get("file_path") or ""
    sl = node.get("start_line")
    el = node.get("end_line")
    if sl and el and el != sl:
        return f"{fp}:{sl}-{el}"
    if sl:
        return f"{fp}:{sl}"
    return fp or "?"


def _empty_comment(reason: str) -> str:
    return "\n".join([
        MARKER,
        "### KnowStack PR review context",
        "",
        f"_{reason}_",
        "",
        "<sub>Generated by `knowstack pr-context`.</sub>",
    ])


# ── io ──────────────────────────────────────────────────────────────────────


def _read_input(argv: list[str]) -> str:
    if len(argv) > 1 and argv[1] != "-":
        return Path(argv[1]).read_text(encoding="utf-8")
    return sys.stdin.read()


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
